export const REQUEST = "REQUEST"
export const SUCCESS = "SUCCESS"
export const FAILURE = "FAILURE"


export const ADDREQUEST = "ADDREQUEST"
export const ADDSUCCESS = "ADDSUCCESS"
export const ADDFAILURE = "ADDFAILURE"

export const UPDATEMUSICRECORDREQUEST = "UPDATEMUSICRECORDREQUEST"
export const UPDATEMUSICRECORDSUCCESS = "UPDATEMUSICRECORDSUCCESS"
export const UPDATEMUSICRECORDFAILURE = "UPDATEMUSICRECORDFAILURE"
